
      PROGRAM MOONLANDER
C SIMPLE MOON LANDER SIMULATION PROGRAM
C :: THIS WILL USE EUATIONS OF MOTION TO GIVE X Y POSITION UPDATES
C    BASED ON INITIAL CONDITIONS AND USER INPUT OF BURN IN X Y 
C    ASSUME: NEWTONIAN MECHANICS
C            Y POSITIVE IS INCREASING ALTITUDE NORMAL TO SURFACE
C            X IS DISTANCE ACCROSS SURFACE
C            Z IS NOT CONSIDERED
C            TIME UPDATES (T) ARE IN 1SECOND INCREMENTS#
C            BURN TIME IS FOR ONE UPDATE(IE 1 SECONDS)
C            X(T) = X0 + V0*T + 1/2*A*T**2
C            F=MASS * ACCELERATION
C            V=0 INITIALLY AND -'VE DOWN
      REAL F, VEHICLEMASS, AY, G 
      REAL T, X, Y,Y0, THRUSTX, THRUSTY, FUELQTY, V, V0
      G=1.625
      X=-100
      Y0=1000
      Y=Y0
      V=0
      V0=0
      T=1
      F=40
      AY=-G
      VEHICLEMASS=100+F
      PRINT *,'INITIAL CONDITIONS'
      PRINT *,'TIME',T,'VELOCITY',V,'ALTITUDE',Y,'FUELMASS',F,'ACC',AY

13    WRITE(*,*)'ENTER THE MAIN ENGINE % THRUST(VERTICAL)'
      READ (*,*)THRUSTY
C 13    THRUSTY=30
C     F=MA
C     A=F/A
      IF (F .LT. 0) THEN
         AY = -G
         F = 0
         PRINT *,'UH OH, FUEL EMPTY!!!!'
      ELSE
         AY =  ((THRUSTY*45.0) / VEHICLEMASS) - G
      END IF

      V = (AY*T)
      Y = Y + V
C     REDUCE MASS BY A FACTOR OF THE THRUSTY     
      IF (F .LT. 0) THEN
         F = 0
      ELSE     
         F = F - (THRUSTY * 0.002)
      END IF

      VEHICLEMASS = 1000.0+F
      PRINT *,'TIME',T,'VELOCITY',V,'ALTITUDE',Y,'FUELMASS',F,'ACC',AY
      T=T+1
      IF (Y .GT. 0) GOTO 13
      IF (V .LT. -1.0) PRINT *,'######## HEAVY LANDING CRASH #########'
      GOTO 41
      IF (V .LT. -0.5) PRINT *,'GOOD LANDING'
41    PRINT *,'END SIMULATION' 
      END
