
      PROGRAM MOONLANDER
C SIMPLE MOON LANDER SIMULATION PROGRAM
C :: THIS WILL USE EUATIONS OF MOTION TO GIVE X Y POSITION UPDATES
C    BASED ON INITIAL CONDITIONS AND USER INPUT OF BURN IN X Y 
C    ASSUME: NEWTONIAN MECHANICS
C            Y POSITIVE IS INCREASING ALTITUDE NORMAL TO SURFACE
C            X IS DISTANCE ACCROSS SURFACE
C            Z IS NOT CONSIDERED
C            TIME UPDATES (T) ARE IN 1SECOND INCREMENTS#
C            BURN TIME IS FOR ONE UPDATE(IE 1 SECONDS)
C            X(T) = X0 + V0*T + 1/2*A*T**2
C            F=MASS * ACCELERATION
C            V=0 INITIALLY AND -'VE DOWN
      REAL F, VEHICLEMASS, AY, G 
      REAL T, X, Y, THRUSTX, THRUSTY, FUELQTY, V
      G=1.625
      X=-100
      Y=1000
      V=0
      T=1
      F=100
      VEHICLEMASS=1000+F
      
13    WRITE(*,*)'ENTER THE MAIN ENGINE % THRUST(VERTICAL)'
      READ (*,*)THRUSTY
      AY=-G+((THRUSTY*150) / VEHICLEMASS)
      Y= Y + (V*T) + (0.5*AY*T**2)
      V= V + AY*T 
     
C     REDUCE MASS BY A FACTOR OF THE THRUSTY      
      F = F - (THRUSTY * 0.05)
      VEHICLEMASS = 1000+FUELMASS
      PRINT *,'TIME',T,'VELOCITY',V,'ALTITUDE',Y,'FUELMASS',F,'ACC',AY
      T=T+1
      IF (Y .GT. 0) GOTO 13
      IF (V .LT. -1.0) PRINT *,'######## HEAVY LANDING CRASH #########'
      GOTO 41
      IF (V .LT. -0.5) PRINT *,'GOOD LANDING'
41    PRINT *,'END SIMULATION' 
      END

